name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[backend]') || contains(github.event.head_commit.message, '[deploy]') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Trigger Render deployment
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "⚠️ RENDER_DEPLOY_HOOK not set. Skipping backend deployment."
            echo "To enable: Add your Render deploy hook URL to GitHub Secrets"
          else
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
            echo "✓ Backend deployment triggered"
          fi
      
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
      
      - name: Verify deployment
        run: |
          if [ -z "${{ secrets.BACKEND_URL }}" ]; then
            echo "⚠️ BACKEND_URL not set. Skipping verification."
          else
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.BACKEND_URL }}/health)
            if [ "$RESPONSE" -eq 200 ]; then
              echo "✓ Backend is healthy"
            else
              echo "❌ Backend health check failed (HTTP $RESPONSE)"
              exit 1
            fi
          fi

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Vercel
        run: |
          echo "✓ Vercel auto-deploys on push to main"
          echo "Check your Vercel dashboard for deployment status"
          echo "URL: https://vercel.com/dashboard"
      
      - name: Notify deployment
        uses: actions/github-script@v6
        with:
          script: |
            const commit = context.payload.head_commit;
            if (commit) {
              console.log(`🚀 Deployment triggered for commit: ${commit.message}`);
            }

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()
    
    steps:
      - name: Send notification
        run: |
          echo "📧 Deployment completed"
          echo "Backend: ${{ needs.deploy-backend.result }}"
          echo "Frontend: ${{ needs.deploy-frontend.result }}"
          
          if [ "${{ needs.deploy-backend.result }}" == "success" ] && [ "${{ needs.deploy-frontend.result }}" == "success" ]; then
            echo "✅ All deployments successful!"
          else
            echo "⚠️ Some deployments failed - check logs"
          fi

